### PR TITLE
Add iframe-resizer

### PR DESCRIPTION
**Pull request by samiheikki**
https://github.com/davidjbradshaw/iframe-resizer

### CODE REVIEW

**Comment by platosha** [comment]
Maybe add it to bower dependencies and include as `../iframe-resizer/js/iframeResizer.js`? Opinions?

**Comment by platosha** [comment]
I like having the `common.html` here, btw. 👍

**Comment by samiheikki** [comment]
Changed it to use bower

**Comment by platosha** [comment]
LGTM :shipit:

**Pull request merged**
