### PR TITLE
Dynamically add anchor to demo titles.

### PR DESCRIPTION
**Pull request by manolo**
Fixes https://github.com/vaadin/vaadin-core-elements/issues/83

### CODE REVIEW

**Review by limonte — APPROVED** [review]
:+1: Sami will be happy :)

**Comment by limonte** [comment]
The only thing I'd add is `margin-left: -26px` for `<a>` tag to keep headers' position (aligned by left with code snippets blocks)

**Comment by manolo** [comment]
Done

**Comment by samiheikki** [comment]
Awesome!

**Pull request merged**
