### PR TITLE
Add ga.js from vaadin-elements and .gitignore

### PR DESCRIPTION
**Pull request by tehapo**
Connects to vaadin/vaadin-grid#180

[Review on Reviewable](https://reviewable.io/reviews/vaadin/elements-demo-resources/3)

### CODE REVIEW

**Comment by tomivirkki** [comment]
_[ga.js, line 13 [r1]](https://reviewable.io:443/reviews/vaadin/elements-demo-resources/3#-K3PtGsKfwWsUuBlu7Wk:-K3PtGsLbcaOwXcwTYMY:1256680571) ([raw file](https://github.com/vaadin/elements-demo-resources/blob/1751c82bb3bcfb5f0b24fefd777ae2c05b51a94c/ga.js#L13)):_
I noticed this file was included in the index pages for both elements. Should the pageViewUrl be modified if pathname doesn't end with /demo/?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/elements-demo-resources/3)_

**Comment by tehapo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[ga.js, line 13 [r1]](https://reviewable.io:443/reviews/vaadin/elements-demo-resources/3#-K3PtGsKfwWsUuBlu7Wk:-K3Th12qcM69Mqrh1Exs:-1584924858) ([raw file](https://github.com/vaadin/elements-demo-resources/blob/1751c82bb3bcfb5f0b24fefd777ae2c05b51a94c/ga.js#L13)):_
Actually, I think we should remove the whole replace logic. Currently the analytics have already been accidentally disabled for the demo pages (other than the index page) and this might be a good cut-off point to switch using the actual page URL instead of adding more replacement logic to match legacy URLs.

Any opinions from @jounik?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/elements-demo-resources/3)_

**Comment by jouni** [comment]
That works for me also. We are not avtively tamravking these numbers right now anyway.

**Comment by tehapo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[ga.js, line 13 [r1]](https://reviewable.io:443/reviews/vaadin/elements-demo-resources/3#-K3PtGsKfwWsUuBlu7Wk:-K3TtF7KzWp4Ca5P0h6y:-1482524940) ([raw file](https://github.com/vaadin/elements-demo-resources/blob/1751c82bb3bcfb5f0b24fefd777ae2c05b51a94c/ga.js#L13)):_
Done. Got rid of the replace logic.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/elements-demo-resources/3)_

**Pull request merged**
